export default [
    {
        id:1,
        postedOn:'2024-12-9',
        title:'iOS Developer',
        company:'Apple',
        type:'Full Time',
        experience:'Mid Level',
        location:'Remote',
        skills:["swiftUI","UIkit","Core Data"],
        job_link:"https://jobs.apple.com/en-in/search?location=chennai-TNH"
    },
    {
        id: 2,
        postedOn: '2024-12-10',
        title: "Frontend Developer",
        type: "Full time",
        location: "In-office",
        experience: "Fresher",
        company: "Amazon",
        skills: ["Javascript", "Nextjs", "Tailwind CSS"],
        job_link: "https://www.amazon.jobs/en/",
      },
      {
        id: 3,
        postedOn: '2024-12-14',
        title: "Android Developer",
        type: "Part time",
        location: "Remote",
        experience: "Senior Level",
        company: "Facebook",
        skills: ["Kotlin", "MVVM"],
        job_link: "https://facebook.com/careers",
      },
      {
        id: 4,
        postedOn: '2024-12-15',
        title: "Developer Advocate",
        type: "Contract",
        location: "Hybrid",
        experience: "Junior Level",
        company: "Netflix",
        skills: ["web3", "Content Creation", "Community"],
        job_link: "https://jobs.netflix.com/",
      },
      {
        id: 5,
        postedOn: '2024-12-13',
        title: "Softwer Developer",
        type: "Full time",
        location: "Hybrid",
        experience: "Senior Level",
        company: "Meta",
        skills: ["c++", "python", "java"],
        job_link: "https://www.metacareers.com/jobs",
      },
]